import type { ObjectId } from "mongodb";

/** Stored image reference (BunnyCDN or local fallback). */
export interface ProductImage {
  url: string;
  fileName: string;
  /** Storage path relative to the zone, used for deletion. */
  storagePath: string;
  uploadDate: Date;
}

export interface Category {
  _id: ObjectId;
  name: string;
  description?: string;
  archived: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface Subcategory {
  _id: ObjectId;
  categoryId: ObjectId;
  name: string;
  description?: string;
  archived: boolean;
  createdAt: Date;
  updatedAt: Date;
}

/** Everything the vision model produced for an item's image (stored as-is). */
export interface AiData {
  /** 3–10 candidate names the model is confident about. */
  names: string[];
  laymanTerms: string[];
  searchKeywords: string[];
  commonNames: string[];
  spellingVariations: string[];
  model: string;
  /** True when generated by the built-in mock rather than a real model. */
  mock: boolean;
  generatedAt: Date;
}

export interface InventoryItem {
  _id: ObjectId;

  // Basic
  /** Primary name. */
  itemName: string;
  /** Additional user-curated names for reference / alternate lookup. */
  referenceNames: string[];
  categoryId: ObjectId | null;
  subcategoryId: ObjectId | null;
  description?: string;
  images: ProductImage[];

  // Search
  searchKeywords: string[];
  aliases: string[];
  commonNames: string[];

  /** Stored AI output for this item's image (null if never analyzed). */
  ai: AiData | null;

  // Stock
  quantity: number;
  unit: string;
  minimumQuantity: number;
  reorderQuantity: number;

  // Location
  warehouse?: string;
  rack?: string;
  shelf?: string;
  bin?: string;

  // Audit
  createdBy: string;
  modifiedBy: string;
  createdAt: Date;
  updatedAt: Date;
}

export type MovementType =
  // Stock In
  | "purchase"
  | "return"
  | "transfer_in"
  // Stock Out
  | "consumption"
  | "sale"
  | "transfer_out"
  | "damaged";

export const STOCK_IN_TYPES: MovementType[] = ["purchase", "return", "transfer_in"];
export const STOCK_OUT_TYPES: MovementType[] = [
  "consumption",
  "sale",
  "transfer_out",
  "damaged",
];

export interface StockMovement {
  _id: ObjectId;
  itemId: ObjectId;
  movementType: MovementType;
  /** Always a positive number; direction is implied by movementType. */
  quantity: number;
  /** Resulting quantity after this movement (snapshot). */
  balanceAfter: number;
  remarks?: string;
  createdBy: string;
  createdAt: Date;
}

/** AI suggestion payload returned by the vision model. */
export interface AiSuggestion {
  suggestedNames: string[];
  searchKeywords: string[];
  commonNames: string[];
  laymanTerms: string[];
  spellingVariations: string[];
  /** Model id that produced the result (or "mock"). */
  model: string;
  /** True when the result came from the local mock, not a real model. */
  mock: boolean;
}

/** JSON-safe versions returned by the API (ObjectId -> string, Date -> ISO). */
export type Serialized<T> = {
  [K in keyof T]: T[K] extends ObjectId
    ? string
    : T[K] extends ObjectId | null
      ? string | null
      : T[K] extends Date
        ? string
        : T[K] extends Date | undefined
          ? string | undefined
          : T[K] extends Array<infer U>
            ? Array<U extends ObjectId ? string : U extends Date ? string : U>
            : T[K];
};

/** Hierarchical storage location (warehouse → rack → shelf → bin). */
export interface Location {
  _id: ObjectId;
  name: string;
  type?: string;
  code?: string;
  description?: string;
  parentLocationId: ObjectId | null;
  isActive: boolean;
  archived: boolean;
  createdAt: Date;
  updatedAt: Date;
}

/** Supplier / vendor master (maps to Agencies in maintenance tracker). */
export interface Supplier {
  _id: ObjectId;
  name: string;
  phone: string;
  email: string;
  notes: string;
  categoryIds: ObjectId[];
  subcategoryIds: ObjectId[];
  isActive: boolean;
  archived: boolean;
  createdAt: Date;
  updatedAt: Date;
}

/** Unit of measure master. */
export interface Unit {
  _id: ObjectId;
  name: string;
  symbol: string;
  description?: string;
  archived: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export type UserRole = "admin" | "staff" | "viewer";

/** Staff / operator master for audit trails. */
export interface User {
  _id: ObjectId;
  name: string;
  email: string;
  phone: string;
  role: UserRole;
  notes: string;
  archived: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export type InformationType = "general" | "note";

/** Reference notes and information log. */
export interface Information {
  _id: ObjectId;
  content: string;
  type: InformationType;
  createdBy: string;
  archived: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export type NotificationRuleType = "low_stock" | "reorder";

/** Stock alert notification rules. */
export interface NotificationRule {
  _id: ObjectId;
  name: string;
  type: NotificationRuleType;
  categoryId: ObjectId | null;
  subcategoryId: ObjectId | null;
  threshold: number;
  notifyEmail: string;
  active: boolean;
  archived: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export type CategoryDTO = Serialized<Category>;
export type SubcategoryDTO = Serialized<Subcategory>;
export type LocationDTO = Serialized<Location>;
export type SupplierDTO = Serialized<Supplier>;
export type UnitDTO = Serialized<Unit>;
export type UserDTO = Serialized<User>;
export type InformationDTO = Serialized<Information>;
export type NotificationRuleDTO = Serialized<NotificationRule>;
export type InventoryItemDTO = Serialized<InventoryItem>;
export type StockMovementDTO = Serialized<StockMovement>;
